#==========================================
#Datos generales
#==========================================

profile: dev
target: dev
#existing_id: ""
warehouse_id: "066cf23804609b70"
benchmark_threshold: 0.5
metric_view_destination: "brz_dev.default"
revert_on_failed_benchmark: true

#==========================================
#Control de flujo
#==========================================
run_validate : false
refactor: true

#==========================================
#config para assessment
#==========================================

business_questions:
  - "¿Cúal es cliente con el precio mas alto?"
  - "¿Cúal es el flete por bolsa mas económico de todos?"
  - "¿Cúal es el top 5 de clientes con mayor descuento por dirección general?"
  - "¿Existe algun cliente que tenga un descuento mayor al 3% en el campo de Descuento asesor?"
  - "¿Dame el precio promedio ponderado de las ventas realizadas el mes pasado (Julio 2026)?"
  - "¿Clientes que tuvieron un caida en las ventas en el mes de Julio 2026?"
  - "¿Cual es el subsegmento que representa el mayor ingreso para el YTD (lo que va del año)?"
  - "Cual es el cliente que tiene un descuento mas bajo comparado con todos los de su mismo grupo (el grupo es Subsegmento, Departamento, Municipio)?"

sources:

 - "brz_dev.star_generico.rentabilidad_honduras"
 - "gld_star_prod.hon.vw_chequeo_precio_inventario_hon"
 - "gld_star_dev.hon.tabladescuentos"



benchmarks:
  questions:
    - id: ""
      question:
        - "¿Dame los ultimos chequeos de precios en la ciudad de Tatumbla?"
      answer:
        - format: "SQL"
          content:
            SELECT *
            FROM gld_star_prod.hon.vw_chequeo_precio_inventario_hon
            WHERE Municipio = 'TATUMBLA'
            ORDER BY Fecha_Creacion DESC
            LIMIT 10;
      evaluation_note:
        - "Debe devolver una tabla con las columnas Nombre_Propietario, Codigo_Cliente, Fecha_Creacion, Proveedor, Marca, Precio_Flete, Precio_Compra, Precio_Venta"

instruccions:
  example_question_sqls:
    - id: ""
      question:
        - "Pregunta de ejemplo"
      sql:
        - "SELECT 1"
      usageguidance:
        - "Cuándo usar esta query"
      parameters:
        - name: "year"
          typehint: "STRING"
          default_value:
            values:
              - "2024"